apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: vista3d-frontend-claim3
  name: vista3d-frontend-claim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
