[project]
name = "nv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "nibabel>=5.3.2",
    "numpy>=2.0.0",
    
    "pydicom>=3.0.1",
    "tqdm>=4.67.1",
    "cryptography>=41.0.0",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.3",
    "bs4>=0.0.2",
    "streamlit>=1.32.0",
    "fastapi>=0.111.0",
    "uvicorn>=0.30.1",
    "open3d>=0.19.0",
    "pyvista>=0.46.3",
    "stpyvista>=0.1.4",
    "scikit-image>=0.25.2",
]
