[project]
name = "nv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=3.2.0",
    "dotenv>=0.9.9",
    "nibabel>=5.3.2",
    "numpy>=2.3.2",
    "pathlib>=1.0.1",
    "pydicom>=3.0.1",
    "tqdm>=4.67.1",
    "cryptography>=41.0.0",
]
