apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: vista3d-server
  name: vista3d-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vista3d-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: vista3d-server
    spec:
      containers:
        - env:
            - name: ALLOW_ABSOLUTE_FILE_PATHS
              value: "True"
            - name: ALLOW_ABSOLUTE_PATHS
              value: "True"
            - name: ALLOW_ANY_HOST
              value: "True"
            - name: ALLOW_ANY_IMAGE_SERVER_HOST
              value: "True"
            - name: ALLOW_ANY_IP_ACCESS
              value: "True"
            - name: ALLOW_ANY_ORIGIN
              value: "True"
            - name: ALLOW_CROSS_ORIGIN
              value: "True"
            - name: ALLOW_EXTERNAL_NETWORK_ACCESS
              value: "True"
            - name: ALLOW_FILE_PROTOCOL
              value: "True"
            - name: ALLOW_HTTPS_ACCESS
              value: "True"
            - name: ALLOW_HTTP_ACCESS
              value: "True"
            - name: ALLOW_IMAGE_SERVER_ACCESS
              value: "True"
            - name: ALLOW_LOCALHOST
              value: "True"
            - name: ALLOW_LOCAL_FILES
              value: "True"
            - name: ALLOW_LOCAL_PATHS
              value: "True"
            - name: ALLOW_LOOPBACK
              value: "True"
            - name: ALLOW_PRIVATE_IPS
              value: "True"
            - name: ALLOW_PUBLIC_IPS
              value: "True"
            - name: ALLOW_RELATIVE_FILE_PATHS
              value: "True"
            - name: ALLOW_RELATIVE_PATHS
              value: "True"
            - name: ALLOW_REMOTE_ACCESS
              value: "True"
            - name: ALLOW_WILDCARD_HOSTS
              value: "True"
            - name: CORS_ALLOW_CREDENTIALS
              value: "True"
            - name: CORS_ALLOW_HEADERS
              value: '*'
            - name: CORS_ALLOW_METHODS
              value: GET,POST,PUT,DELETE,OPTIONS
            - name: CORS_ALLOW_ORIGINS
              value: '*'
            - name: CORS_EXPOSE_HEADERS
              value: '*'
            - name: CORS_MAX_AGE
              value: "3600"
            - name: CUDA_LAUNCH_BLOCKING
              value: "1"
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
            - name: DISABLE_CORS
              value: "True"
            - name: DISABLE_DOMAIN_WHITELIST
              value: "True"
            - name: DISABLE_HOST_VALIDATION
              value: "True"
            - name: DISABLE_IMAGE_SERVER_VALIDATION
              value: "True"
            - name: DISABLE_IP_VALIDATION
              value: "True"
            - name: DISABLE_NETWORK_RESTRICTIONS
              value: "True"
            - name: DISABLE_ORIGIN_VALIDATION
              value: "True"
            - name: DISABLE_URL_VALIDATION
              value: "True"
            - name: DOMAIN_WHITELIST
              value: '[".*","http://.*","https://.*","http://.*:.*","https://.*:.*","file:///.*","*"]'
            - name: ENABLE_CONTAINER_PATHS
              value: "True"
            - name: ENABLE_EXTERNAL_ACCESS
              value: "True"
            - name: ENABLE_FILE_ACCESS
              value: "True"
            - name: FILE_ACCESS_MODE
              value: local
            - name: IGNORE_SSL_ERRORS
              value: "True"
            - name: IMAGE_SERVER
              value: http://localhost:8888
            - name: IMAGE_URI_ALLOW_REDIRECTS
              value: "True"
            - name: IMAGE_URI_HTTPS_ONLY
              value: "False"
            - name: LOCAL_FILE_ACCESS
              value: "True"
            - name: LOCAL_NIM_CACHE
              value: /workspace/.cache/nim
            - name: NGC_API_KEY
            - name: NGC_ORG_ID
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"
            - name: SUPPORTED_IMAGE_EXT
              value: '[".nrrd",".nii",".nii.gz",".dcm"]'
            - name: TORCH_USE_CUDA_DSA
              value: "1"
            - name: VISTA3D_ALLOW_ANY_URL
              value: "True"
            - name: VISTA3D_ALLOW_EXTERNAL_IMAGES
              value: "True"
            - name: VISTA3D_ALLOW_HTTPS_DOWNLOADS
              value: "True"
            - name: VISTA3D_ALLOW_HTTP_DOWNLOADS
              value: "True"
            - name: VISTA3D_ALLOW_INSECURE_CONNECTIONS
              value: "True"
            - name: VISTA3D_ALLOW_REMOTE_FILES
              value: "True"
            - name: VISTA3D_DISABLE_FILE_VALIDATION
              value: "True"
            - name: VISTA3D_DISABLE_IMAGE_VALIDATION
              value: "True"
            - name: VISTA3D_DISABLE_SSL_VERIFICATION
              value: "True"
            - name: VISTA3D_DISABLE_URL_VALIDATION
              value: "True"
            - name: VISTA3D_ENABLE_NETWORK_ACCESS
              value: "True"
            - name: VISTA3D_MAX_RETRIES
              value: "3"
            - name: VISTA3D_SERVER
              value: http://localhost:8000
            - name: VISTA3D_TIMEOUT
              value: "300"
            - name: WORKSPACE_IMAGES_PATH
              value: /workspace/output/nifti
            - name: WORKSPACE_OUTPUTS_PATH
              value: /workspace/output
            - name: WORKSPACE_ROOT
              value: /workspace
          image: nvcr.io/nim/nvidia/vista3d:1.0.0
          name: vista3d-server-standalone
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace/output
              name: vista3d-server-claim0
      restartPolicy: Always
      volumes:
        - name: vista3d-server-claim0
          persistentVolumeClaim:
            claimName: vista3d-server-claim0
