apiVersion: apps/v1
kind: Deployment
metadata:
  name: vista3d-frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: vista3d
      app.kubernetes.io/name: vista3d
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: vista3d
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vista3d
        app.kubernetes.io/part-of: vista3d
    spec:
      containers:
      - env:
        - name: IMAGE_SERVER
          value: http://vista3d-image-server:8888
        - name: EXTERNAL_IMAGE_SERVER
          value: http://vista3d-image-server:8888
        - name: VISTA3D_IMAGE_SERVER_URL
          value: http://vista3d-image-server:8888
        - name: OUTPUT_FOLDER
          value: /app/output
        - name: DICOM_FOLDER
          value: /app/dicom
        - name: VISTA3D_SERVER
          value: http://vista3d-backend:8000
        - name: DOCKER_CONTAINER
          value: "false"
        - name: STREAMLIT_SERVER_RUN_ON_SAVE
          value: "true"
        - name: STREAMLIT_SERVER_FILE_WATCHER_TYPE
          value: auto
        - name: UV_CACHE_DIR
          value: /tmp/.uv_cache
        image: localhost:32000/vista3d-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: vista3d-frontend
        ports:
        - containerPort: 8501
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/output
          name: output-data
        - mountPath: /app/dicom
          name: dicom-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: vista3d
      serviceAccountName: vista3d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: output-data
        persistentVolumeClaim:
          claimName: vista3d-output-pvc
      - name: dicom-data
        persistentVolumeClaim:
          claimName: vista3d-dicom-pvc
