apiVersion: apps/v1
kind: Deployment
metadata:
  name: vista3d-image-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: image-server
      app.kubernetes.io/instance: vista3d
      app.kubernetes.io/name: vista3d
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: image-server
        app.kubernetes.io/instance: vista3d
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vista3d
        app.kubernetes.io/part-of: vista3d
    spec:
      containers:
      - env:
        - name: OUTPUT_FOLDER
          value: /data/output
        - name: DICOM_FOLDER
          value: /data/dicom
        - name: IMAGE_SERVER
          value: http://localhost:8888
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        image: localhost:32000/vista3d-image-server:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: vista3d-image-server
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/output
          name: output-data
          readOnly: true
        - mountPath: /data/dicom
          name: dicom-data
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: vista3d
      serviceAccountName: vista3d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: output-data
        persistentVolumeClaim:
          claimName: vista3d-output-pvc
      - name: dicom-data
        persistentVolumeClaim:
          claimName: vista3d-dicom-pvc
