apiVersion: v2
name: vista3d
description: HPE NVIDIA Vista3D Medical AI Platform - AI-powered medical image segmentation with 3D visualization
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/dw-flyingw/HPE-Nvidia-Vista-3D
sources:
  - https://github.com/dw-flyingw/HPE-Nvidia-Vista-3D
maintainers:
  - name: HPE Helathcare AI Team
    email: dave.wright@hpe.com
keywords:
  - medical-imaging
  - ai
  - segmentation
  - nvidia
  - vista3d
  - dicom
  - nifti
  - 3d-visualization
annotations:
  category: Healthcare
  licenses: Apache-2.0
dependencies:
  - name: nginx-ingress
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
