apiVersion: v2
name: vista3d
description: HPE NVIDIA Vista3D Medical AI Platform - Frontend and Image Server for microk8s deployment
type: application
version: 1.3.0
appVersion: "1.3.0"
home: https://github.com/dw-flyingw/HPE-Nvidia-Vista-3D
sources:
  - https://github.com/dw-flyingw/HPE-Nvidia-Vista-3D
maintainers:
  - name: HPE Healthcare AI Team
    email: dave.wright@hpe.com
keywords:
  - medical-imaging
  - ai
  - segmentation
  - nvidia
  - vista3d
  - dicom
  - nifti
  - 3d-visualization
annotations:
  category: Healthcare
  licenses: Apache-2.0
  # Note: This chart expects an ingress controller to be pre-installed
  # if ingress.enabled is set to true. Recommended: NGINX Ingress Controller
