# Default values for vista3d
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageRegistry: ""
  imagePullSecrets: []

backend:
  enabled: false
  name: vista3d-backend
  replicaCount: 1
  image:
    repository: nvcr.io/nim/nvidia/vista3d
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

frontend:
  enabled: true
  name: vista3d-frontend
  replicaCount: 1
  image:
    repository: dwtwp/vista3d-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8501
    targetPort: 8501
  env:
    IMAGE_SERVER: "http://vista3d-image-server:8888"
    EXTERNAL_IMAGE_SERVER: "http://vista3d-image-server:8888"
    VISTA3D_IMAGE_SERVER_URL: "http://vista3d-image-server:8888"
    OUTPUT_FOLDER: "/app/output"
    DICOM_FOLDER: "/app/dicom"
    DOCKER_CONTAINER: "true"
    STREAMLIT_SERVER_RUN_ON_SAVE: "true"
    STREAMLIT_SERVER_FILE_WATCHER_TYPE: "auto"
  volumeMounts:
    - name: output-data
      mountPath: /app/output
    - name: dicom-data
      mountPath: /app/dicom

imageServer:
  enabled: true
  name: vista3d-image-server
  replicaCount: 1
  image:
    repository: dwtwp/vista3d-image-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8888
    targetPort: 8888
  env:
    OUTPUT_FOLDER: "/data/output"
    DICOM_FOLDER: "/data/dicom"
    IMAGE_SERVER: "http://localhost:8888" # This is for the image server itself, not the frontend
    PYTHONUNBUFFERED: "1"
    PYTHONDONTWRITEBYTECODE: "1"
  volumeMounts:
    - name: output-data
      mountPath: /data/output
      readOnly: true
    - name: dicom-data
      mountPath: /data/dicom
      readOnly: true

persistence:
  enabled: true
  output:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Gi
  dicom:
    enabled: true
    accessMode: ReadOnlyMany
    size: 50Gi

sampleData:
  enabled: true
  url: "https://github.com/dw-flyingw/HPE-Nvidia-Vista-3D/releases/download/v1.0.0/sample_data.tgz"

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  create: true
  ngcApiKey: "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" # User must provide their NGC API Key here or via --set

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: vista3d.local
      paths:
        - path: /
          pathType: Prefix
  tls: []