# Frontend and Image Server deployment for local development/testing
# This configuration disables the backend component

backend:
  enabled: false

imageServer:
  enabled: true

# Enable persistence with ReadWriteOnce (required for minikube)
persistence:
  enabled: true
  output:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi  # Reduced size for local testing
  dicom:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi  # Reduced size for local testing

# Override security context to run as root (required for local development)
# The frontend image needs write access to /app and cache directories
# Note: Image server uses default security context (user 1000)
frontend:
  podSecurityContext:
    runAsUser: 0
    runAsNonRoot: false
    fsGroup: 0
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false

# Image server runs as unprivileged user (matches Dockerfile USER directive)
imageServer:
  podSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
