[server]
headless = true
port = 8501
address = "0.0.0.0"
# baseUrlPath = "/vista3d"  # NOT needed - nginx strips the prefix before forwarding

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#05a883"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
