{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vista3d.backend.deploymentName" . }}
  labels:
    app.kubernetes.io/name: {{ include "vista3d.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: vista3d
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vista3d.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vista3d.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: vista3d
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vista3d.serviceAccountName" . }}
      securityContext:
        {{- if .Values.backend.podSecurityContext }}
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
        - name: vista3d-backend
          image: "{{ .Values.global.imageRegistry }}{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          securityContext:
            {{- if .Values.backend.securityContext }}
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: NGC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "vista3d.fullname" . }}-secrets
                  key: ngc-api-key
            - name: NGC_ORG_ID
              value: "nvidia"
            - name: LOCAL_NIM_CACHE
              value: "/workspace/.cache/nim"
            - name: VISTA3D_SERVER
              value: "http://localhost:8000"
            - name: WORKSPACE_IMAGES_PATH
              value: "/workspace/output/nifti"
            - name: WORKSPACE_OUTPUTS_PATH
              value: "/workspace/output"
            - name: WORKSPACE_ROOT
              value: "/workspace"
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: SUPPORTED_IMAGE_EXT
              value: '".nrrd",".nii",".nii.gz",".dcm"'
            - name: IMAGE_SERVER
              value: "http://vista3d-image-server:8888"
            - name: ALLOW_LOCAL_FILES
              value: "True"
            - name: ENABLE_FILE_ACCESS
              value: "True"
            - name: ALLOW_ABSOLUTE_PATHS
              value: "True"
            - name: ALLOW_RELATIVE_PATHS
              value: "True"
            - name: ALLOW_FILE_PROTOCOL
              value: "True"
            - name: ALLOW_LOCAL_PATHS
              value: "True"
            - name: CORS_ALLOW_ORIGINS
              value: "*"
            - name: CORS_ALLOW_METHODS
              value: "GET,POST,PUT,DELETE,OPTIONS"
            - name: CORS_ALLOW_HEADERS
              value: "*"
            - name: CORS_ALLOW_CREDENTIALS
              value: "True"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.backend.volumeMounts | nindent 12 }}
      volumes:
        - name: output-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-output-pvc
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
