apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vista3d.fullname" . }}
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
data:
  IMAGE_SERVER: "http://{{ .Values.imageServer.name }}:{{ .Values.imageServer.service.port }}"
  EXTERNAL_IMAGE_SERVER: "http://{{ .Values.imageServer.name }}:{{ .Values.imageServer.service.port }}"
  VISTA3D_IMAGE_SERVER_URL: "http://{{ .Values.imageServer.name }}:{{ .Values.imageServer.service.port }}"
  OUTPUT_FOLDER: "/app/output"
  DICOM_FOLDER: "/app/dicom"
  DOCKER_CONTAINER: "true"
  STREAMLIT_SERVER_RUN_ON_SAVE: "true"
  STREAMLIT_SERVER_FILE_WATCHER_TYPE: "auto"