{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vista3d.fullname" . }}-frontend
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "vista3d.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "vista3d.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: IMAGE_SERVER
              value: "http://{{ .Values.imageServer.name }}:{{ .Values.imageServer.service.port }}"
            - name: EXTERNAL_IMAGE_SERVER
              value: "http://localhost:8888"
            - name: VISTA3D_IMAGE_SERVER_URL
              value: "http://{{ .Values.imageServer.name }}:{{ .Values.imageServer.service.port }}"
            - name: OUTPUT_FOLDER
              value: {{ .Values.frontend.env.OUTPUT_FOLDER | quote }}
            - name: DICOM_FOLDER
              value: {{ .Values.frontend.env.DICOM_FOLDER | quote }}
            - name: DOCKER_CONTAINER
              value: {{ .Values.frontend.env.DOCKER_CONTAINER | quote }}
            - name: STREAMLIT_SERVER_RUN_ON_SAVE
              value: {{ .Values.frontend.env.STREAMLIT_SERVER_RUN_ON_SAVE | quote }}
            - name: STREAMLIT_SERVER_FILE_WATCHER_TYPE
              value: {{ .Values.frontend.env.STREAMLIT_SERVER_FILE_WATCHER_TYPE | quote }}
          volumeMounts:
            {{- toYaml .Values.frontend.volumeMounts | nindent 12 }}
      volumes:
        - name: output-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-output-pvc
        - name: dicom-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-dicom-pvc
{{- end }}