{{- if .Values.imageServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vista3d.fullname" . }}-image-server
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-server
spec:
  replicas: {{ .Values.imageServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "vista3d.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: image-server
  template:
    metadata:
      labels:
        {{- include "vista3d.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: image-server
    spec:
      containers:
        - name: {{ .Values.imageServer.name }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.imageServer.image.repository }}:{{ .Values.imageServer.image.tag }}"
          imagePullPolicy: {{ .Values.imageServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.imageServer.service.port }}
              protocol: TCP
          env:
            - name: OUTPUT_FOLDER
              value: {{ .Values.imageServer.env.OUTPUT_FOLDER | quote }}
            - name: DICOM_FOLDER
              value: {{ .Values.imageServer.env.DICOM_FOLDER | quote }}
            - name: IMAGE_SERVER
              value: {{ .Values.imageServer.env.IMAGE_SERVER | quote }}
            - name: PYTHONUNBUFFERED
              value: {{ .Values.imageServer.env.PYTHONUNBUFFERED | quote }}
            - name: PYTHONDONTWRITEBYTECODE
              value: {{ .Values.imageServer.env.PYTHONDONTWRITEBYTECODE | quote }}
          volumeMounts:
            {{- toYaml .Values.imageServer.volumeMounts | nindent 12 }}
      volumes:
        - name: output-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-output-pvc
        - name: dicom-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-dicom-pvc
{{- end }}