{{- if .Values.imageServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vista3d.imageServer.deploymentName" . }}
  labels:
    app.kubernetes.io/name: {{ include "vista3d.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: image-server
    app.kubernetes.io/part-of: vista3d
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.imageServer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vista3d.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: image-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vista3d.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: image-server
        app.kubernetes.io/part-of: vista3d
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vista3d.serviceAccountName" . }}
      securityContext:
        {{- if .Values.imageServer.podSecurityContext }}
        {{- toYaml .Values.imageServer.podSecurityContext | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
        - name: vista3d-image-server
          image: "{{ .Values.global.imageRegistry }}{{ .Values.imageServer.image.repository }}:{{ .Values.imageServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageServer.image.pullPolicy }}
          securityContext:
            {{- if .Values.imageServer.securityContext }}
            {{- toYaml .Values.imageServer.securityContext | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          env:
            {{- toYaml .Values.imageServer.env | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.imageServer.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.imageServer.volumeMounts | nindent 12 }}
      volumes:
        - name: output-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-output-pvc
        - name: dicom-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-dicom-pvc
      {{- with .Values.imageServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imageServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imageServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
