{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: vista3d-secrets
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.ngcApiKey }}
  ngc-api-key: {{ .Values.secrets.ngcApiKey | b64enc | quote }}
  {{- else }}
  ngc-api-key: {{ "your-ngc-api-key-here" | b64enc | quote }}
  {{- end }}
{{- else if .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecret }}
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
type: Opaque
data:
  ngc-api-key: {{ "your-ngc-api-key-here" | b64enc | quote }}
{{- end }}
