apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: image-server-claim4
  name: image-server-claim4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
